<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

# Lab 3.1.1 
# *Data Wrangling and Munging with Pandas*

## Part 1: Wrangling Data

The term "data wrangling" is analogous to capturing wild horses and getting them into a fenced area; the horses are data and the fencing is your computer. The more common data wrangling tasks include:

- reading flat files
- reading Excel files
- downloading from web pages
  - csv
  - html
  - json

In [1]:
import numpy as np
import pandas as pd

*It is good practice to display the library version numbers for future reference:*

In [2]:
print('Numpy: ', np.__version__)
print('Pandas: ', pd.__version__)

Numpy:  1.18.5
Pandas:  1.0.5


### CSV Files

Below are three attempts to load the file "bikeshare.csv" into a DataFrame named `bikes`. Why are they wrong?

In [4]:
# wrong:
bikes = pd.read_table('C:\\Data Science\\My Datasets\\bikeshare.csv', header = None)
print(bikes.head())
print()

# wrong:
bikes = pd.read_table('C:\\Data Science\\My Datasets\\bikeshare.csv', header = 1)
print(bikes.head())
print()

# wrong:
bikes = pd.read_table('C:\\Data Science\\My Datasets\\bikeshare.csv', header = 0)
print(bikes.head())

                                                   0
0  instant,dteday,season,yr,mnth,hr,holiday,weekd...
1  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,...
2  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...
3  3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.8,0...
4  4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,...

  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0,3,13,16
0  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...     
1  3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.8,0...     
2  4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,...     
3  5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,...     
4  6,2011-01-01,1,0,1,5,0,6,0,2,0.24,0.2576,0.75,...     

  instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,...                                                                   
1  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...                                        

?:
ANSWER: Case 1 treats headings as just another data row. Case 2 treats the 1st data row as the column header. Case 3 gets the header right (row 0), but reads each row as a single column (Nb. the other two make that same mistake). 

Load the file "bikeshare.csv" into a DataFrame named `bikes`, and confirm that it was loaded properly:

In [5]:
#ANSWER:
import pandas as pd
df_bikes = pd.read_table('C:\\Data Science\\My Datasets\\bikeshare.csv',delimiter=',', index_col=0, header = 0)
df_bikes.head()


dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
instant                                                                   
1        2011-01-01       1   0     1   0        0        6           0   
2        2011-01-01       1   0     1   1        0        6           0   
3        2011-01-01       1   0     1   2        0        6           0   
4        2011-01-01       1   0     1   3        0        6           0   
5        2011-01-01       1   0     1   4        0        6           0   

         weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
instant                                                                      
1                 1  0.24  0.2879  0.81        0.0       3          13   16  
2                 1  0.22  0.2727  0.80        0.0       8          32   40  
3                 1  0.22  0.2727  0.80        0.0       5          27   32  
4                 1  0.24  0.2879  0.75        0.0       3          10   13  
5                 1  0.24  0.2879  0.75        0.0       0           1    1

Note that we could have used `read.csv()` above. When is `read_table()` necessary?

?:
ANSWER: When `sep` is not the comma character, or we need fine control that `read.csv()` does not provide.

Flat files can be full of surprises. Here are some issues to watch out for:

- separator character is something other than the comma
  - ";", "|", and tab are popular
- newline character is something other than what the O/S expects 
  - Tip: Don't hard-code the character codes for carriage returns, linefeeds, etc. Use Python's built-in representation instead (e.g. Python translates "\n" to the newline character and "\t" to the tab character on any O/S).
- truncated lines
  - if there are empty fields at the end of a line it is possible that their separators will be missing, resulting in a "jagged" file
- embedded commas or quotes
  - a free-text field containing embedded commas may split into separate fields on input
  - a free-text field containing embedded quotes may not parse correctly
- unescaped characters
  - the "\" character indicates a control code to Python, which will break the I/O
    - e.g. the substring "\u0123" will be interpreted as Unicode(0123) -- which may not be what the file creator intended
  - these may need to be fixed by loading whole strings and then parsing into a new data frame
  
Tip: Most issues can be delth with by correctly specifying the parameters of the function you use to load the file. Read the doco before reading the data!

### Reading Excel Files

In [6]:
from pandas import ExcelFile  # Nb. Need to install xlrd from conda (it does not automatically install with pandas)

In [7]:
from pandas import ExcelFile
df_iris = pd.read_excel('C:\\Data Science\\My Datasets\\Iris.xls', sheet_name = 'Data')
df_iris

Species_No  Petal_width  Petal_length  Sepal_width  Sepal_length  \
0             1          0.2           1.4          3.5           5.1   
1             1          0.2           1.4          3.0           4.9   
2             1          0.2           1.3          3.2           4.7   
3             1          0.2           1.5          3.1           4.6   
4             1          0.2           1.4          3.6           5.0   
..          ...          ...           ...          ...           ...   
145           3          2.3           5.2          3.0           6.7   
146           3          1.9           5.0          2.5           6.3   
147           3          2.0           5.2          3.0           6.5   
148           3          2.3           5.4          3.4           6.2   
149           3          1.8           5.1          3.0           5.9   

    Species_name  
0         Setosa  
1         Setosa  
2         Setosa  
3         Setosa  
4         Setosa  
..           ...  
145    Verginica  
146    Verginica  
147    Verginica  
148    Verginica  
149    Verginica  

[150 rows x 6 columns]

So, this file appears to have an embedded table of aggregates on the same sheet as the raw data (a naughty but common practice amongst analysts).

It is usually better to load data correctly than to meddle with the source file or load it 'warts and all' and then try to parse it in code. The Pandas functions for reading files have parameters that provide the control we need. For ecxample, we could make multiple calls to `read_excel()`, using combinations of the `header`, `usecols`, `skiprows`, `nrows`, and `skipfooter` parameters to load one table at a time from a spreadsheet with multiple tables.

Load the above file without the unwanted columns:

In [8]:
#ANSWER
from pandas import ExcelFile
df_iris = pd.read_excel('C:\\Data Science\\My Datasets\\Iris.xls', sheet_name = 'Data', usecols = [0, 1, 2, 3, 4] )
df_iris

Species_No  Petal_width  Petal_length  Sepal_width  Sepal_length
0             1          0.2           1.4          3.5           5.1
1             1          0.2           1.4          3.0           4.9
2             1          0.2           1.3          3.2           4.7
3             1          0.2           1.5          3.1           4.6
4             1          0.2           1.4          3.6           5.0
..          ...          ...           ...          ...           ...
145           3          2.3           5.2          3.0           6.7
146           3          1.9           5.0          2.5           6.3
147           3          2.0           5.2          3.0           6.5
148           3          2.3           5.4          3.4           6.2
149           3          1.8           5.1          3.0           5.9

[150 rows x 5 columns]

### Importing Data Directly from the Web

We usually want to store a local copy of a data file that we download from the Web, but when data retention is not a priority it is convenient to download the data directly into our running Python environment.

#### Importing Text Files from the Web

The web is the 'wild west' of data formats. However, we can usually expect good behaviour from files that are automatically generated by a service, such as the earthquake report:

In [9]:
df = pd.read_csv('https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_hour.csv')
df.head()

time  latitude  longitude  depth   mag magType  nst  \
0  2020-07-11T07:55:13.670Z   17.9358   -66.9123     13  3.23      md   19   

   gap    dmin   rms  ...                   updated  \
0  209  0.0514  0.15  ...  2020-07-11T08:24:14.440Z   

                            place        type horizontalError depthError  \
0  3 km S of Guánica, Puerto Rico  earthquake            0.69        0.3   

   magError  magNst    status  locationSource magSource  
0      0.15      18  reviewed              pr        pr  

[1 rows x 22 columns]

#### Importing HTML Files from the Web

Working with unstructured HTML files relies heavily on library functions. This one, however, is well-structured:

In [10]:
url = 'http://www.fdic.gov/bank/individual/failed/banklist.html'
df = pd.read_html(url)
df[0]

Bank Name           City  ST   CERT  \
0                 The First State Bank  Barboursville  WV  14361   
1                   Ericson State Bank        Ericson  NE  18265   
2     City National Bank of New Jersey         Newark  NJ  21111   
3                        Resolute Bank         Maumee  OH  58317   
4                Louisa Community Bank         Louisa  KY  58112   
..                                 ...            ...  ..    ...   
556                 Superior Bank, FSB       Hinsdale  IL  32646   
557                Malta National Bank          Malta  OH   6629   
558    First Alliance Bank & Trust Co.     Manchester  NH  34264   
559  National State Bank of Metropolis     Metropolis  IL   3815   
560                   Bank of Honolulu       Honolulu  HI  21029   

                   Acquiring Institution       Closing Date  
0                         MVB Bank, Inc.      April 3, 2020  
1             Farmers and Merchants Bank  February 14, 2020  
2                        Industrial Bank   November 1, 2019  
3                     Buckeye State Bank   October 25, 2019  
4      Kentucky Farmers Bank Corporation   October 25, 2019  
..                                   ...                ...  
556                Superior Federal, FSB      July 27, 2001  
557                    North Valley Bank        May 3, 2001  
558  Southern New Hampshire Bank & Trust   February 2, 2001  
559              Banterra Bank of Marion  December 14, 2000  
560                   Bank of the Orient   October 13, 2000  

[561 rows x 6 columns]

#### Importing XML Files from the Web

XML files are semi-structured, but you're at the mercy of the file creator. If every record has the same format it will be much easier, but practical applications often require a lot of custom code. Here is an example that includes a nice parser class: http://www.austintaylor.io/lxml/python/pandas/xml/dataframe/2016/07/08/convert-xml-to-pandas-dataframe/

#### Importing JSON Files from the Web

Like XML, JSON files are semi-structured and may require work to capture the schema into a dataframe. Here is a simple example: 

In [11]:
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/data.json'

# Load the first sheet of the JSON file into a data frame
df = pd.read_json(url, orient = 'columns')
df.head()

integer            datetime  category
0        5 2015-01-01 00:00:00         0
1        5 2015-01-01 00:00:01         0
2        9 2015-01-01 00:00:02         0
3        6 2015-01-01 00:00:03         0
4        6 2015-01-01 00:00:04         0

## Part 2: Data Munging

Data munging is manipulating data to get it into a form that we can start running analyses on (which usually means getting the data into a DataFrame). Before we get to this stage, we may need to remove headers or footers, transpose columns to rows, split wide data tables into long ones, and so on. (Nb. Excel files can be particularly troublesome, because users can format their data in mixed, complex shapes.) Essentially, we need to follow Hadley Wickham's guidelines for tidy datasets (http://vita.had.co.nz/papers/tidy-data.html):

The end goal of the cleaning data process:

- each variable should be in one column
- each observation should comprise one row
- each type of observational unit should form one table
- include key columns for linking multiple tables
- the top row contains (sensible) variable names
- in general, save data as one file per table


### Dataset Morphology

Once we have our dataset in a DataFrame (or Series, if our data is only 1-dimensional), we can start examining its size and content.

How many rows and columns are in `bikes`?

In [12]:
#ANSWER
df_bikes.shape

(17379, 16)

What are the column names in `bikes`?

In [13]:
#ANSWER
df_bikes.columns

Index(['dteday', 'season', 'yr', 'mnth', 'hr', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
       'casual', 'registered', 'cnt'],
      dtype='object')

What are the data types of these columns?

In [14]:
#ANSWER
df_bikes.dtypes

dteday         object
season          int64
yr              int64
mnth            int64
hr              int64
holiday         int64
weekday         int64
workingday      int64
weathersit      int64
temp          float64
atemp         float64
hum           float64
windspeed     float64
casual          int64
registered      int64
cnt             int64
dtype: object

What is the (row) index for this DataFrame?

In [15]:
#ANSWER
df_bikes.index

Int64Index([    1,     2,     3,     4,     5,     6,     7,     8,     9,
               10,
            ...
            17370, 17371, 17372, 17373, 17374, 17375, 17376, 17377, 17378,
            17379],
           dtype='int64', name='instant', length=17379)

https://www.dataquest.io/blog/python-json-tutorial/

## Slicing and Dicing

It is often preferable to refer to DataFrame columns by name, but there is more than one way to do this. 
Do `bikes['season']` and `bikes[['season']]` give the same object? Demonstrate:

In [16]:
#ANSWER
print (type(df_bikes[['season']]))
print (type(df_bikes['season']))


<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


How would we use object notation to show the first 4 rows of `atemp`?

In [17]:
#ANSWER
df_bikes[['atemp']][:4]

atemp
instant        
1        0.2879
2        0.2727
3        0.2727
4        0.2879

Algorithms that loop over multiple columns often access DataFrame columns by index. However, none of the following work (try them out by uncommenting / removing the "#E: " ): 

In [18]:
df_bikes[:]
# df_bikes[0]
# df_bikes[0,0]
# df_bikes[[0,0]]

dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
instant                                                                   
1        2011-01-01       1   0     1   0        0        6           0   
2        2011-01-01       1   0     1   1        0        6           0   
3        2011-01-01       1   0     1   2        0        6           0   
4        2011-01-01       1   0     1   3        0        6           0   
5        2011-01-01       1   0     1   4        0        6           0   
...             ...     ...  ..   ...  ..      ...      ...         ...   
17375    2012-12-31       1   1    12  19        0        1           1   
17376    2012-12-31       1   1    12  20        0        1           1   
17377    2012-12-31       1   1    12  21        0        1           1   
17378    2012-12-31       1   1    12  22        0        1           1   
17379    2012-12-31       1   1    12  23        0        1           1   

         weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
instant                                                                      
1                 1  0.24  0.2879  0.81     0.0000       3          13   16  
2                 1  0.22  0.2727  0.80     0.0000       8          32   40  
3                 1  0.22  0.2727  0.80     0.0000       5          27   32  
4                 1  0.24  0.2879  0.75     0.0000       3          10   13  
5                 1  0.24  0.2879  0.75     0.0000       0           1    1  
...             ...   ...     ...   ...        ...     ...         ...  ...  
17375             2  0.26  0.2576  0.60     0.1642      11         108  119  
17376             2  0.26  0.2576  0.60     0.1642       8          81   89  
17377             1  0.26  0.2576  0.60     0.1642       7          83   90  
17378             1  0.26  0.2727  0.56     0.1343      13          48   61  
17379             1  0.26  0.2727  0.65     0.1343      12          37   49  

[17379 rows x 16 columns]

What is the correct way to access the 1st row of the DataFrame by its index?

In [19]:
#ANSWER
df_bikes[:1]

dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
instant                                                                   
1        2011-01-01       1   0     1   0        0        6           0   

         weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
instant                                                                      
1                 1  0.24  0.2879  0.81        0.0       3          13   16

What is the correct way to access the 2nd column of the DataFrame by its index?

In [20]:
#ANSWER
df_bikes.iloc[:,1]

instant
1        1
2        1
3        1
4        1
5        1
        ..
17375    1
17376    1
17377    1
17378    1
17379    1
Name: season, Length: 17379, dtype: int64

## Handling Missing Values

What is the Pandas `isnull` function for? 

?
ANSWER:

We can apply `isnull` to the `bikes` DataFrame to show the result for every element:

In [21]:
df_bikes.isnull().head()

dteday  season     yr   mnth     hr  holiday  weekday  workingday  \
instant                                                                      
1         False   False  False  False  False    False    False       False   
2         False   False  False  False  False    False    False       False   
3         False   False  False  False  False    False    False       False   
4         False   False  False  False  False    False    False       False   
5         False   False  False  False  False    False    False       False   

         weathersit   temp  atemp    hum  windspeed  casual  registered    cnt  
instant                                                                         
1             False  False  False  False      False   False       False  False  
2             False  False  False  False      False   False       False  False  
3             False  False  False  False      False   False       False  False  
4             False  False  False  False      False   False       False  False  
5             False  False  False  False      False   False       False  False

However, we usually start at a higher level. How many nulls are in `bikes` altogether?

In [23]:
#ANSWER
df_bikes.isnull().sum()

dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

If this result were nonzero we would next want to find out which columns contained nulls. How can this be done in one line of code?

In [24]:
#ANSWER
df_bikes.isnull().sum()

dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

What is the Numpy object `nan` used for? (Write a descriptive answer.)

NaN , standing for not a number, is a numeric data type used to represent any value that is undefined or unpresentable. For example, 0/0 is undefined as a real number and is, therefore, represented by NaN.

Further, with numpy, you can use nan to represent missing or invalid values. nan is a floating point constant that numpy reserves and treats specially. Numpy designed nan so that nan == nan returns False, but nan != nan returns True.
This is because equivalence between missing or invalid values is not well defined. In practice, this behavior prevents silent bugs from creeping into your program. 

In order to see which elements of bot are nan, you can use numpy’s isnan() function.
It’s important to note that nan only works for an array of floats. If you try inserting nan into an array of integers, booleans, or strings, you’ll get an error or unexpected behavior.

Write (and verify) a function that performs scalar division with built-in handling of the edge case (i.e. return a value instead of just trapping the error):

In [30]:
#ANSWER
import numpy as np
def divide(dividend, divisor):
    if divisor == 0:
        quotient = np.nan
    else:
        quotient = dividend / divisor
    return (quotient)

print(divide(1, 0))

nan


Apply the Pandas `isna` function to the following data objects:

In [31]:
x = 2.3
y = np.nan
print(x, y)

2.3 nan


In [32]:
#ANSWER
print(pd.isna(x), pd.isna(y))

False True


In [33]:
array = np.array([[1, np.nan, 3], [4, 5, np.nan]])
print(array)

[[ 1. nan  3.]
 [ 4.  5. nan]]


In [34]:
#ANSWER
pd.isna(array)

array([[False,  True, False],
       [False, False,  True]])

How is the pandas I/O parameter `na_values` used?

If you want any additional strings to be considered as NaN, other than the default NaN values, then use na_values. If you pass None value to na_values, the default NA values are used. If you pass a dict mapping column names to values, then those values will be used for those columns, totally overriding the default NA values, while for columns not in the dict, the default values will be used. If you pass some other kind of iterable, it uses the union of the passed values and the default values as the NA values.

## Data Profiling

### Counts

When there are categorical variables in a dataset we will want to know how many possible values there are in each column. (Nb. If the dataset is a sample of a larger one, our sample may not capture all possible values of every categorical.)

How many (different) seasons are in `bikes`?

In [36]:
#ANSWER
df_bikes['season'].value_counts()

3    4496
2    4409
1    4242
4    4232
Name: season, dtype: int64

### Ranges

Print the range of the `instant`, `dteday`, and `windspeed` columns: 

In [39]:
df_bikes = pd.read_csv('C:\\Data Science\\My Datasets\\bikeshare.csv')

In [40]:
#ANSWER

print('instant min():', df_bikes['instant'].min(), 'and instant max()', df_bikes['instant'].max())
print('dteday min():', df_bikes['dteday'].min(), ' and dteday max()', df_bikes['dteday'].max())
print('windspeed min()', df_bikes['windspeed'].min(), ' and windspeed max()', df_bikes['windspeed'].max())

instant min(): 1 and instant max() 17379
dteday min(): 2011-01-01  and dteday max() 2012-12-31
windspeed min() 0.0  and windspeed max() 0.8507


Compute and print the overall minimum and maximum of the numeric data columns:

In [41]:
bikes_min, bikes_max = (min(df_bikes.min(numeric_only=True)), 
                        max(df_bikes.max(numeric_only=True)))
bikes_min, bikes_max

(0.0, 17379.0)

### Quantiles

Pandas makes computing quantiles easy. This is how to get the median of a Series:

In [42]:
df_bikes['atemp'].quantile(0.5)

0.4848

Of course, the `quantiles` method can take a tuple as its argument. Compute the 10th, 25th, 50th, 75th, and 90th percentiles in one line of code: 

In [43]:
#ANSWER
df_bikes['atemp'].quantile((0.1, 0.25, 0.5, 0.75, 0.9))

0.10    0.2424
0.25    0.3333
0.50    0.4848
0.75    0.6212
0.90    0.6970
Name: atemp, dtype: float64

### Cuts

Sometimes we want to split the sample not by the quantiles of the distribution but by the range of the data. Let's take a closer look at `atemp`:

In [44]:
type(df_bikes['atemp'])

pandas.core.series.Series

In [81]:
df_bikes.sample(5)

dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
instant                                                                   
5707     2011-08-31       3   0     8   5        0        3           1   
253      2011-01-11       1   0     1  21        0        2           1   
2558     2011-04-21       2   0     4  11        0        4           1   
14991    2012-09-21       3   1     9  19        0        5           1   
14754    2012-09-11       3   1     9  22        0        2           1   

         weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
instant                                                                      
5707              1  0.54  0.5152  0.83     0.0896       2          25   27  
253               3  0.16  0.1970  0.86     0.0896       0          20   20  
2558              1  0.44  0.4394  0.41     0.2836      34          99  133  
14991             1  0.64  0.6061  0.65     0.2537      95         493  588  
14754             1  0.56  0.5303  0.64     0.1045      27         189  216

Suppose we decide to sort these values into 4 bins of equal width, but we want to apply the resulting groups to the entire DataFrame. Basically, we need to add a row label that indcates which bin each sample belongs in. Let's call this label "atemp_level", and use the `cut` method to populate it:

In [84]:
atemp_level = pd.cut(df_bikes['atemp'], bins = 4)         

What is `atemp_level`?

In [85]:
#ANSWER
print(type(atemp_level))

<class 'pandas.core.series.Series'>


Here is a random sample of `atemp_level`:

In [0]:
atemp_level.sample(5)          

So, by default, `cut` produces labels that indicate the bin boundaries for each element in the series it was applied to. Usually, we will specify labels that are appropriate to the discretisation we are applying:

In [86]:
atemp_level = pd.cut(df_bikes['atemp'], bins = 4, labels = ["cool", "mild", "warm", "hot"])
atemp_level.sample(5)          

instant
10776    mild
12309    warm
13444    warm
14256    warm
1674     mild
Name: atemp, dtype: category
Categories (4, object): [cool < mild < warm < hot]

Incorporate the new `atemp_level` column into the `bikes` DataFrame and use it to count the number of "mild" `atemp` entries in `season` 2:

In [89]:
#ANSWER
df_bikes['atemp_level'] = atemp_level
df_bikes[(df_bikes.atemp_level == 'mild') & (df_bikes.season == 2)].season.count() 

1829

*Nb. The `atemp_level` variable we created is what the R language calls a "factor". Pandas has introduced a new data type called "category" that is similar to R's factors.*

# Synthetic Data

Sometimes we may want to generate test data, or we may need to initalise a series, matrix, or data frame for input to an algorithm. Numpy has several methods we can use for this.

Execute the following, then check the shape and content of each variable:

In [91]:
# Creating arrays with initial values
a = np.zeros((3))
b = np.ones((1,3))
c = np.random.randint(1,10,(2,3,4))   # randint(low, high, size)
d = np.arange(4)
e = np.array( [[1,2,3,4], [5,6,7,8]] )

In [94]:
# Cleaning Data
print('a Shape = {0}'.format(a.shape))
print (a)
print('b Shape = {0}'.format(b.shape))
print (b)
print('c Shape = {0}'.format(c.shape))
print (c)
print('d Shape = {0}'.format(d.shape))
print (d)
print('e Shape = {0}'.format(e.shape))
print (e)

a Shape = (3,)
[0. 0. 0.]
b Shape = (1, 3)
[[1. 1. 1.]]
c Shape = (2, 3, 4)
[[[6 4 4 9]
  [4 9 6 9]
  [4 7 6 2]]

 [[2 9 4 4]
  [5 4 3 8]
  [3 2 7 9]]]
d Shape = (4,)
[0 1 2 3]
e Shape = (2, 4)
[[1 2 3 4]
 [5 6 7 8]]


## Load Data

Load rock.csv and clean the dataset.

In [96]:
df_rock = pd.read_csv('C:\\Data Science\\My Datasets\\rock.csv')
df_rock.head()

Song Clean ARTIST CLEAN Release Year  \
0        Caught Up in You  .38 Special         1982   
1            Fantasy Girl  .38 Special          NaN   
2         Hold On Loosely  .38 Special         1981   
3  Rockin' Into the Night  .38 Special         1980   
4       Art For Arts Sake         10cc         1975   

                                COMBINED  First?  Year?  PlayCount  F*G  
0        Caught Up in You by .38 Special       1      1         82   82  
1            Fantasy Girl by .38 Special       1      0          3    0  
2         Hold On Loosely by .38 Special       1      1         85   85  
3  Rockin' Into the Night by .38 Special       1      1         18   18  
4              Art For Arts Sake by 10cc       1      1          1    1

## Check Column Names

Check column names and clean.

In [99]:
df_rock.columns
def clean_column_name(column_names):
    clean_column_names = []
    for c in column_names:
        c = c.lower().replace(' ', '_')
        c = c.lower().replace('*', '')
        c = c.lower().replace('?', '')
        clean_column_names.append(c)
        
    return clean_column_names
df_rock.columns = clean_column_name(df_rock.columns)
df_rock.columns

Index(['song_clean', 'artist_clean', 'release_year', 'combined', 'first',
       'year', 'playcount', 'fg'],
      dtype='object')

# Replace Null Values With 0

Check 'release' column whether this column have any null value or not. Replace null value with 0.

In [103]:
print(df_rock.isnull().sum())
df_rock.loc[df_rock.release_year.isnull(),'release_year'] = 0  
print(df_rock.isnull().sum())

song_clean        0
artist_clean      0
release_year    577
combined          0
first             0
year              0
playcount         0
fg                0
dtype: int64
song_clean      0
artist_clean    0
release_year    0
combined        0
first           0
year            0
playcount       0
fg              0
dtype: int64


# Check Datatypes of Dataset

Check datatypes of the dataset. Is there any column which should be int instead of object? Fix the column. 

In [105]:
df_rock.dtypes

song_clean      object
artist_clean    object
release_year    object
combined        object
first            int64
year             int64
playcount        int64
fg               int64
dtype: object

In [108]:
df_rock.loc[df_rock.release_year == 'SONGFACTS.COM', 'release_year'] = np.NaN
df_rock['release_year'] = pd.to_numeric(df_rock['release_year'])
df_rock.dtypes

C:\Users\Muham\anaconda3\lib\site-packages\pandas\core\ops\array_ops.py:253: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  res_values = method(rvalues)


song_clean       object
artist_clean     object
release_year    float64
combined         object
first             int64
year              int64
playcount         int64
fg                int64
dtype: object

# Check Min, Max of Each Column

Is there any illogical value in any column? How can we fix that?

In [112]:
df_rock.describe().T[['min','max']]

min     max
release_year  0.0  2014.0
first         1.0     1.0
year          0.0     1.0
playcount     0.0   142.0
fg            0.0   142.0

In [117]:
df_rock.loc[df_rock.release_year==0, 'release_year'] = np.NaN
df_rock.loc[df_rock.release_year==1071, 'release_year'] = np.NaN
df_rock.describe().T[['min','max']]

min     max
release_year  1955.0  2014.0
first            1.0     1.0
year             0.0     1.0
playcount        0.0   142.0
fg               0.0   142.0

# Write Some Functions

In [118]:
df_rock.dtypes

song_clean       object
artist_clean     object
release_year    float64
combined         object
first             int64
year              int64
playcount         int64
fg                int64
dtype: object

## Write a function that will take a row of a DataFrame and print out the song, artist, and whether or not the release date is < 1970

In [119]:
def print_info (dfrow):
    print('Song: {0}, Artist: {1}, Earlier then 1970: {2}\n'.format(dfrow['song_clean'],dfrow['song_clean'], dfrow['release_year']<1970))

print_info(df_rock.iloc[0])

Song: Caught Up in You, Artist: Caught Up in You, Earlier then 1970: False



## Write a function that converts cells in a DataFrame to float and otherwise replaces them with np.nan

In [120]:
def convert_to_numeric (col):
    column = pd.to_numeric(col, errors='coerce')
    return column

## Apply these functions to your dataset

In [121]:
df_rock.apply(convert_to_numeric)

song_clean  artist_clean  release_year  combined  first  year  \
0            NaN           NaN        1982.0       NaN      1     1   
1            NaN           NaN           NaN       NaN      1     0   
2            NaN           NaN        1981.0       NaN      1     1   
3            NaN           NaN        1980.0       NaN      1     1   
4            NaN           NaN        1975.0       NaN      1     1   
...          ...           ...           ...       ...    ...   ...   
2225         NaN           NaN           NaN       NaN      1     0   
2226         NaN           NaN        1981.0       NaN      1     1   
2227         NaN           NaN        1975.0       NaN      1     1   
2228         NaN           NaN        1983.0       NaN      1     1   
2229         NaN           NaN        1973.0       NaN      1     1   

      playcount   fg  
0            82   82  
1             3    0  
2            85   85  
3            18   18  
4             1    1  
...         ...  ...  
2225          1    0  
2226         32   32  
2227        109  109  
2228          1    1  
2229          2    2  

[2230 rows x 8 columns]

## Describe the new float-only DataFrame.

In [122]:
df_rock.describe().T

count         mean        std     min     25%     50%     75%  \
release_year  1651.0  1978.569352   9.309780  1955.0  1971.0  1977.0  1984.0   
first         2230.0     1.000000   0.000000     1.0     1.0     1.0     1.0   
year          2230.0     0.741256   0.438043     0.0     0.0     1.0     1.0   
playcount     2230.0    16.872646  25.302972     0.0     1.0     4.0    21.0   
fg            2230.0    15.048430  25.288366     0.0     0.0     3.0    18.0   

                 max  
release_year  2014.0  
first            1.0  
year             1.0  
playcount      142.0  
fg             142.0



> 
>
>




>


>


>




---



---



> > > > > > > > > © 2019 Institute of Data


---



---



