In [5]:
import pandas as pd
import numpy as np

Importing data

In [45]:
hcdata = pd.read_csv('C:\\Users\\Owner\\Downloads\\hcvdat0.csv')
print(hcdata)

     Unnamed: 0       Category  Age Sex   ALB    ALP    ALT    AST   BIL  \
0             1  0=Blood Donor   32   m  38.5   52.5    7.7   22.1   7.5   
1             2  0=Blood Donor   32   m  38.5   70.3   18.0   24.7   3.9   
2             3  0=Blood Donor   32   m  46.9   74.7   36.2   52.6   6.1   
3             4  0=Blood Donor   32   m  43.2   52.0   30.6   22.6  18.9   
4             5  0=Blood Donor   32   m  39.2   74.1   32.6   24.8   9.6   
..          ...            ...  ...  ..   ...    ...    ...    ...   ...   
610         611    3=Cirrhosis   62   f  32.0  416.6    5.9  110.3  50.0   
611         612    3=Cirrhosis   64   f  24.0  102.8    2.9   44.4  20.0   
612         613    3=Cirrhosis   64   f  29.0   87.3    3.5   99.0  48.0   
613         614    3=Cirrhosis   46   f  33.0    NaN   39.0   62.0  20.0   
614         615    3=Cirrhosis   59   f  36.0    NaN  100.0   80.0  12.0   

       CHE  CHOL   CREA    GGT  PROT  
0     6.93  3.23  106.0   12.1  69.0  
1    11.1

In [7]:
hcdata.head(10)

Unnamed: 0       Category  Age Sex   ALB   ALP   ALT   AST   BIL    CHE  \
0           1  0=Blood Donor   32   m  38.5  52.5   7.7  22.1   7.5   6.93   
1           2  0=Blood Donor   32   m  38.5  70.3  18.0  24.7   3.9  11.17   
2           3  0=Blood Donor   32   m  46.9  74.7  36.2  52.6   6.1   8.84   
3           4  0=Blood Donor   32   m  43.2  52.0  30.6  22.6  18.9   7.33   
4           5  0=Blood Donor   32   m  39.2  74.1  32.6  24.8   9.6   9.15   
5           6  0=Blood Donor   32   m  41.6  43.3  18.5  19.7  12.3   9.92   
6           7  0=Blood Donor   32   m  46.3  41.3  17.5  17.8   8.5   7.01   
7           8  0=Blood Donor   32   m  42.2  41.9  35.8  31.1  16.1   5.82   
8           9  0=Blood Donor   32   m  50.9  65.5  23.2  21.2   6.9   8.69   
9          10  0=Blood Donor   32   m  42.4  86.3  20.3  20.0  35.2   5.46   

   CHOL   CREA   GGT  PROT  
0  3.23  106.0  12.1  69.0  
1  4.80   74.0  15.6  76.5  
2  5.20   86.0  33.2  79.3  
3  4.74   80.0  33.8  75.7  
4  4.32   76.0  29.9  68.7  
5  6.05  111.0  91.0  74.0  
6  4.79   70.0  16.9  74.5  
7  4.60  109.0  21.5  67.1  
8  4.10   83.0  13.7  71.3  
9  4.45   81.0  15.9  69.9

Viewing the class distribution

In [8]:
hcdata.groupby('Category')['Age'].count()

Category
0=Blood Donor             533
0s=suspect Blood Donor      7
1=Hepatitis                24
2=Fibrosis                 21
3=Cirrhosis                30
Name: Age, dtype: int64

In [9]:
hcdata.dtypes

Unnamed: 0      int64
Category       object
Age             int64
Sex            object
ALB           float64
ALP           float64
ALT           float64
AST           float64
BIL           float64
CHE           float64
CHOL          float64
CREA          float64
GGT           float64
PROT          float64
dtype: object

Handling missing values

In [10]:
hcdata.isnull().sum().sum()

31

In [11]:
hcdata.isnull().sum()

Unnamed: 0     0
Category       0
Age            0
Sex            0
ALB            1
ALP           18
ALT            1
AST            0
BIL            0
CHE            0
CHOL          10
CREA           0
GGT            0
PROT           1
dtype: int64

In [12]:
hcdata['ALP'].fillna(0,inplace=True)
hcdata['ALB'].fillna(0,inplace=True)
hcdata['ALT'].fillna(0,inplace=True)
hcdata['CHOL'].fillna(0,inplace=True)
hcdata['PROT'].fillna(0,inplace=True)

In [13]:
hcdata.isnull().sum()

Unnamed: 0    0
Category      0
Age           0
Sex           0
ALB           0
ALP           0
ALT           0
AST           0
BIL           0
CHE           0
CHOL          0
CREA          0
GGT           0
PROT          0
dtype: int64

Encoding categorical data

In [14]:
hcdata["Category"].value_counts()

0=Blood Donor             533
3=Cirrhosis                30
1=Hepatitis                24
2=Fibrosis                 21
0s=suspect Blood Donor      7
Name: Category, dtype: int64

In [15]:
hcdata["Category"] = hcdata["Category"].astype('category')
hcdata.dtypes

Unnamed: 0       int64
Category      category
Age              int64
Sex             object
ALB            float64
ALP            float64
ALT            float64
AST            float64
BIL            float64
CHE            float64
CHOL           float64
CREA           float64
GGT            float64
PROT           float64
dtype: object

In [16]:
hcdata["Category_coded"] = hcdata["Category"].cat.codes
hcdata.head()

Unnamed: 0       Category  Age Sex   ALB   ALP   ALT   AST   BIL    CHE  \
0           1  0=Blood Donor   32   m  38.5  52.5   7.7  22.1   7.5   6.93   
1           2  0=Blood Donor   32   m  38.5  70.3  18.0  24.7   3.9  11.17   
2           3  0=Blood Donor   32   m  46.9  74.7  36.2  52.6   6.1   8.84   
3           4  0=Blood Donor   32   m  43.2  52.0  30.6  22.6  18.9   7.33   
4           5  0=Blood Donor   32   m  39.2  74.1  32.6  24.8   9.6   9.15   

   CHOL   CREA   GGT  PROT  Category_coded  
0  3.23  106.0  12.1  69.0               0  
1  4.80   74.0  15.6  76.5               0  
2  5.20   86.0  33.2  79.3               0  
3  4.74   80.0  33.8  75.7               0  
4  4.32   76.0  29.9  68.7               0

In [17]:
hcdata["Category"].value_counts()

0=Blood Donor             533
3=Cirrhosis                30
1=Hepatitis                24
2=Fibrosis                 21
0s=suspect Blood Donor      7
Name: Category, dtype: int64

In [18]:
hcdata["Category_coded"].value_counts()

0    533
4     30
2     24
3     21
1      7
Name: Category_coded, dtype: int64

In [19]:
hcdata["Sex"] = hcdata["Sex"].astype('category')
hcdata.dtypes
hcdata["Sex_coded"] = hcdata["Sex"].cat.codes
hcdata.head()

Unnamed: 0       Category  Age Sex   ALB   ALP   ALT   AST   BIL    CHE  \
0           1  0=Blood Donor   32   m  38.5  52.5   7.7  22.1   7.5   6.93   
1           2  0=Blood Donor   32   m  38.5  70.3  18.0  24.7   3.9  11.17   
2           3  0=Blood Donor   32   m  46.9  74.7  36.2  52.6   6.1   8.84   
3           4  0=Blood Donor   32   m  43.2  52.0  30.6  22.6  18.9   7.33   
4           5  0=Blood Donor   32   m  39.2  74.1  32.6  24.8   9.6   9.15   

   CHOL   CREA   GGT  PROT  Category_coded  Sex_coded  
0  3.23  106.0  12.1  69.0               0          1  
1  4.80   74.0  15.6  76.5               0          1  
2  5.20   86.0  33.2  79.3               0          1  
3  4.74   80.0  33.8  75.7               0          1  
4  4.32   76.0  29.9  68.7               0          1

In [20]:
hcdata.drop(['Sex','Category'],axis=1,inplace=True)

In [21]:
hcdata.head()

Unnamed: 0  Age   ALB   ALP   ALT   AST   BIL    CHE  CHOL   CREA   GGT  \
0           1   32  38.5  52.5   7.7  22.1   7.5   6.93  3.23  106.0  12.1   
1           2   32  38.5  70.3  18.0  24.7   3.9  11.17  4.80   74.0  15.6   
2           3   32  46.9  74.7  36.2  52.6   6.1   8.84  5.20   86.0  33.2   
3           4   32  43.2  52.0  30.6  22.6  18.9   7.33  4.74   80.0  33.8   
4           5   32  39.2  74.1  32.6  24.8   9.6   9.15  4.32   76.0  29.9   

   PROT  Category_coded  Sex_coded  
0  69.0               0          1  
1  76.5               0          1  
2  79.3               0          1  
3  75.7               0          1  
4  68.7               0          1

In [22]:
from imblearn.over_sampling import SMOTE

In [23]:
oversample = SMOTE()

In [24]:
y = hcdata['Category_coded']

In [25]:
y

0      0
1      0
2      0
3      0
4      0
      ..
610    4
611    4
612    4
613    4
614    4
Name: Category_coded, Length: 615, dtype: int8

In [26]:
x = hcdata.drop(['Category_coded','Unnamed: 0'],axis=1)

In [27]:
x.head()

Age   ALB   ALP   ALT   AST   BIL    CHE  CHOL   CREA   GGT  PROT  \
0   32  38.5  52.5   7.7  22.1   7.5   6.93  3.23  106.0  12.1  69.0   
1   32  38.5  70.3  18.0  24.7   3.9  11.17  4.80   74.0  15.6  76.5   
2   32  46.9  74.7  36.2  52.6   6.1   8.84  5.20   86.0  33.2  79.3   
3   32  43.2  52.0  30.6  22.6  18.9   7.33  4.74   80.0  33.8  75.7   
4   32  39.2  74.1  32.6  24.8   9.6   9.15  4.32   76.0  29.9  68.7   

   Sex_coded  
0          1  
1          1  
2          1  
3          1  
4          1

In [28]:
x, y = oversample.fit_resample(x, y)


In [29]:
np.bincount(y)

array([533, 533, 533, 533, 533], dtype=int64)

In [30]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [31]:
X_train, X_test, y_train, y_test = train_test_split(x, y, random_state=1)

In [32]:
logreg = LogisticRegression(multi_class='ovr',max_iter=10000)
logreg.fit(X_train, y_train)

LogisticRegression(max_iter=10000, multi_class='ovr')

In [33]:
#logreg.coef_
y_pred = logreg.predict(X_test)

In [34]:
#logreg.intercept_

In [35]:
print('accuracy = {:7.4f}'.format(logreg.score(X_train, y_train)))

accuracy =  0.9059


In [36]:
#print('accuracy = {:7.4f}'.format(logreg.score(X_test, y_pred)))

In [37]:
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_test, y_pred)
print('Confusion Matrix\n')
print(confusion)

Confusion Matrix

[[114   0   1   2   2]
 [  0 128   0   0   0]
 [  4   0 127  17   6]
 [  3   0  23 105   0]
 [  0   0   0   8 127]]


In [38]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_test, y_pred)))

print('Micro Precision: {:.2f}'.format(precision_score(y_test, y_pred, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_test, y_pred, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_test, y_pred, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_test, y_pred, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_test, y_pred, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_test, y_pred, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_test, y_pred, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_test, y_pred, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_test, y_pred, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_test, y_pred, target_names=['Class 1', 'Class 2', 'Class 3','Class 4','Class 5']))



Accuracy: 0.90

Micro Precision: 0.90
Micro Recall: 0.90
Micro F1-score: 0.90

Macro Precision: 0.90
Macro Recall: 0.90
Macro F1-score: 0.90

Weighted Precision: 0.90
Weighted Recall: 0.90
Weighted F1-score: 0.90

Classification Report

              precision    recall  f1-score   support

     Class 1       0.94      0.96      0.95       119
     Class 2       1.00      1.00      1.00       128
     Class 3       0.84      0.82      0.83       154
     Class 4       0.80      0.80      0.80       131
     Class 5       0.94      0.94      0.94       135

    accuracy                           0.90       667
   macro avg       0.90      0.90      0.90       667
weighted avg       0.90      0.90      0.90       667



In [39]:
from sklearn.svm import SVC
model = SVC(decision_function_shape='ovo')
# fit model
model.fit(X_train, y_train)
# make predictions
y_pred = model.predict(X_test)

In [40]:
confusion = confusion_matrix(y_test, y_pred)
print('Confusion Matrix\n')
print(confusion)

Confusion Matrix

[[115   3   1   0   0]
 [  0 128   0   0   0]
 [  3   0 128  21   2]
 [  0   0   8 123   0]
 [  0   0   4  13 118]]


In [41]:
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_test, y_pred)))

print('Micro Precision: {:.2f}'.format(precision_score(y_test, y_pred, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_test, y_pred, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_test, y_pred, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_test, y_pred, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_test, y_pred, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_test, y_pred, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_test, y_pred, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_test, y_pred, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_test, y_pred, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_test, y_pred, target_names=['Class 1', 'Class 2', 'Class 3','Class 4','Class 5']))


Accuracy: 0.92

Micro Precision: 0.92
Micro Recall: 0.92
Micro F1-score: 0.92

Macro Precision: 0.93
Macro Recall: 0.92
Macro F1-score: 0.92

Weighted Precision: 0.92
Weighted Recall: 0.92
Weighted F1-score: 0.92

Classification Report

              precision    recall  f1-score   support

     Class 1       0.97      0.97      0.97       119
     Class 2       0.98      1.00      0.99       128
     Class 3       0.91      0.83      0.87       154
     Class 4       0.78      0.94      0.85       131
     Class 5       0.98      0.87      0.93       135

    accuracy                           0.92       667
   macro avg       0.93      0.92      0.92       667
weighted avg       0.92      0.92      0.92       667



In [42]:
from sklearn.multiclass import OneVsRestClassifier
clf = OneVsRestClassifier(SVC()).fit(X_train, y_train)
y_pred = clf.predict(X_test)

In [43]:
confusion = confusion_matrix(y_test, y_pred)
print('Confusion Matrix\n')
print(confusion)

Confusion Matrix

[[114   4   0   0   1]
 [  0 128   0   0   0]
 [  3   0 131  19   1]
 [  6   0  14 111   0]
 [  0   0   4  11 120]]


In [44]:
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_test, y_pred)))

print('Micro Precision: {:.2f}'.format(precision_score(y_test, y_pred, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_test, y_pred, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_test, y_pred, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_test, y_pred, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_test, y_pred, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_test, y_pred, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_test, y_pred, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_test, y_pred, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_test, y_pred, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_test, y_pred, target_names=['Class 1', 'Class 2', 'Class 3','Class 4','Class 5']))


Accuracy: 0.91

Micro Precision: 0.91
Micro Recall: 0.91
Micro F1-score: 0.91

Macro Precision: 0.91
Macro Recall: 0.91
Macro F1-score: 0.91

Weighted Precision: 0.91
Weighted Recall: 0.91
Weighted F1-score: 0.91

Classification Report

              precision    recall  f1-score   support

     Class 1       0.93      0.96      0.94       119
     Class 2       0.97      1.00      0.98       128
     Class 3       0.88      0.85      0.86       154
     Class 4       0.79      0.85      0.82       131
     Class 5       0.98      0.89      0.93       135

    accuracy                           0.91       667
   macro avg       0.91      0.91      0.91       667
weighted avg       0.91      0.91      0.91       667

