<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

# Lab 3.1.1 
# *Data Wrangling and Munging with Pandas*

## Part 1: Wrangling Data

The term "data wrangling" is analogous to capturing wild horses and getting them into a fenced area; the horses are data and the fencing is your computer. The more common data wrangling tasks include:

- reading flat files
- reading Excel files
- downloading from web pages
  - csv
  - html
  - json

In [1]:
import numpy as np
import pandas as pd

*It is good practice to display the library version numbers for future reference:*

In [2]:
print('Numpy: ', np.__version__)
print('Pandas: ', pd.__version__)

Numpy:  1.18.1
Pandas:  0.24.2


### CSV Files

Below are three attempts to load the file "bikeshare.csv" into a DataFrame named `bikes`. Why are they wrong?

In [3]:
# wrong:
bikes = pd.read_table('~/Desktop/bikeshare.csv', header = None)
print(bikes.head())
print()

# wrong:
bikes = pd.read_table('~/Desktop/bikeshare.csv', header = 1)
print(bikes.head())
print()

# wrong:
bikes = pd.read_table('~/Desktop/bikeshare.csv', header = 0)
print(bikes.head())

                                                   0
0  instant,dteday,season,yr,mnth,hr,holiday,weekd...
1  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,...
2  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...
3  3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.8,0...
4  4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,...

  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0,3,13,16
0  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...     
1  3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.8,0...     
2  4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,...     
3  5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,...     
4  6,2011-01-01,1,0,1,5,0,6,0,2,0.24,0.2576,0.75,...     

  instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,...                                                                   
1  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...                                        

C:\Users\wibby\anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  
C:\Users\wibby\anaconda3\lib\site-packages\ipykernel_launcher.py:7: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  import sys
C:\Users\wibby\anaconda3\lib\site-packages\ipykernel_launcher.py:12: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  if sys.path[0] == '':


?:
ANSWER: Case 1 treats headings as just another data row. Case 2 treats the 1st data row as the column header. Case 3 gets the header right (row 0), but reads each row as a single column (Nb. the other two make that same mistake). 

Load the file "bikeshare.csv" into a DataFrame named `bikes`, and confirm that it was loaded properly:

In [4]:
#ANSWER:
bikes = pd.read_csv('~/Desktop/bikeshare.csv', sep = ',', index_col = None)
bikes.head()


instant      dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1   0        0        6           0   
1        2  2011-01-01       1   0     1   1        0        6           0   
2        3  2011-01-01       1   0     1   2        0        6           0   
3        4  2011-01-01       1   0     1   3        0        6           0   
4        5  2011-01-01       1   0     1   4        0        6           0   

   weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
0           1  0.24  0.2879  0.81        0.0       3          13   16  
1           1  0.22  0.2727  0.80        0.0       8          32   40  
2           1  0.22  0.2727  0.80        0.0       5          27   32  
3           1  0.24  0.2879  0.75        0.0       3          10   13  
4           1  0.24  0.2879  0.75        0.0       0           1    1

Note that we could have used `read.csv()` above. When is `read_table()` necessary?

?:
ANSWER: When `sep` is not the comma character, or we need fine control that `read.csv()` does not provide.

Flat files can be full of surprises. Here are some issues to watch out for:

- separator character is something other than the comma
  - ";", "|", and tab are popular
- newline character is something other than what the O/S expects 
  - Tip: Don't hard-code the character codes for carriage returns, linefeeds, etc. Use Python's built-in representation instead (e.g. Python translates "\n" to the newline character and "\t" to the tab character on any O/S).
- truncated lines
  - if there are empty fields at the end of a line it is possible that their separators will be missing, resulting in a "jagged" file
- embedded commas or quotes
  - a free-text field containing embedded commas may split into separate fields on input
  - a free-text field containing embedded quotes may not parse correctly
- unescaped characters
  - the "\" character indicates a control code to Python, which will break the I/O
    - e.g. the substring "\u0123" will be interpreted as Unicode(0123) -- which may not be what the file creator intended
  - these may need to be fixed by loading whole strings and then parsing into a new data frame
  
Tip: Most issues can be delth with by correctly specifying the parameters of the function you use to load the file. Read the doco before reading the data!

### Reading Excel Files

In [5]:
from pandas import ExcelFile  # Nb. Need to install xlrd from conda (it does not automatically install with pandas)

In [73]:
df = pd.read_excel('~/Desktop/Iris.xls', sheet_name = 'Data')
df

Species_No  Petal_width  Petal_length  Sepal_width  Sepal_length  \
0             1          0.2           1.4          3.5           5.1   
1             1          0.2           1.4          3.0           4.9   
2             1          0.2           1.3          3.2           4.7   
3             1          0.2           1.5          3.1           4.6   
4             1          0.2           1.4          3.6           5.0   
5             1          0.4           1.7          3.9           5.4   
6             1          0.3           1.4          3.4           4.6   
7             1          0.2           1.5          3.4           5.0   
8             1          0.2           1.4          2.9           4.4   
9             1          0.1           1.5          3.1           4.9   
10            1          0.2           1.5          3.7           5.4   
11            1          0.2           1.6          3.4           4.8   
12            1          0.1           1.4          3.0           4.8   
13            1          0.1           1.1          3.0           4.3   
14            1          0.2           1.2          4.0           5.8   
15            1          0.4           1.5          4.4           5.7   
16            1          0.4           1.3          3.9           5.4   
17            1          0.3           1.4          3.5           5.1   
18            1          0.3           1.7          3.8           5.7   
19            1          0.3           1.5          3.8           5.1   
20            1          0.2           1.7          3.4           5.4   
21            1          0.4           1.5          3.7           5.1   
22            1          0.2           1.0          3.6           4.6   
23            1          0.5           1.7          3.3           5.1   
24            1          0.2           1.9          3.4           4.8   
25            1          0.2           1.6          3.0           5.0   
26            1          0.4           1.6          3.4           5.0   
27            1          0.2           1.5          3.5           5.2   
28            1          0.2           1.4          3.4           5.2   
29            1          0.2           1.6          3.2           4.7   
..          ...          ...           ...          ...           ...   
120           3          2.3           5.7          3.2           6.9   
121           3          2.0           4.9          2.8           5.6   
122           3          2.0           6.7          2.8           7.7   
123           3          1.8           4.9          2.7           6.3   
124           3          2.1           5.7          3.3           6.7   
125           3          1.8           6.0          3.2           7.2   
126           3          1.8           4.8          2.8           6.2   
127           3          1.8           4.9          3.0           6.1   
128           3          2.1           5.6          2.8           6.4   
129           3          1.6           5.8          3.0           7.2   
130           3          1.9           6.1          2.8           7.4   
131           3          2.0           6.4          3.8           7.9   
132           3          2.2           5.6          2.8           6.4   
133           3          1.5           5.1          2.8           6.3   
134           3          1.4           5.6          2.6           6.1   
135           3          2.3           6.1          3.0           7.7   
136           3          2.4           5.6          3.4           6.3   
137           3          1.8           5.5          3.1           6.4   
138           3          1.8           4.8          3.0           6.0   
139           3          2.1           5.4          3.1           6.9   
140           3          2.4           5.6          3.1           6.7   
141           3          2.3           5.1          3.1           6.9   
142           3          1.9           5.1          2.7        

So, this file appears to have an embedded table of aggregates on the same sheet as the raw data (a naughty but common practice amongst analysts).

It is usually better to load data correctly than to meddle with the source file or load it 'warts and all' and then try to parse it in code. The Pandas functions for reading files have parameters that provide the control we need. For ecxample, we could make multiple calls to `read_excel()`, using combinations of the `header`, `usecols`, `skiprows`, `nrows`, and `skipfooter` parameters to load one table at a time from a spreadsheet with multiple tables.

Load the above file without the unwanted columns:

In [7]:
#ANSWER
df_setosa = pd.read_excel('~/Desktop/Iris.xls', sheet_name = 'Data', usecols= range(0,5), skipfooter = 100)
df_setosa

Species_No  Petal_width  Petal_length  Sepal_width  Sepal_length
0            1          0.2           1.4          3.5           5.1
1            1          0.2           1.4          3.0           4.9
2            1          0.2           1.3          3.2           4.7
3            1          0.2           1.5          3.1           4.6
4            1          0.2           1.4          3.6           5.0
5            1          0.4           1.7          3.9           5.4
6            1          0.3           1.4          3.4           4.6
7            1          0.2           1.5          3.4           5.0
8            1          0.2           1.4          2.9           4.4
9            1          0.1           1.5          3.1           4.9
10           1          0.2           1.5          3.7           5.4
11           1          0.2           1.6          3.4           4.8
12           1          0.1           1.4          3.0           4.8
13           1          0.1           1.1          3.0           4.3
14           1          0.2           1.2          4.0           5.8
15           1          0.4           1.5          4.4           5.7
16           1          0.4           1.3          3.9           5.4
17           1          0.3           1.4          3.5           5.1
18           1          0.3           1.7          3.8           5.7
19           1          0.3           1.5          3.8           5.1
20           1          0.2           1.7          3.4           5.4
21           1          0.4           1.5          3.7           5.1
22           1          0.2           1.0          3.6           4.6
23           1          0.5           1.7          3.3           5.1
24           1          0.2           1.9          3.4           4.8
25           1          0.2           1.6          3.0           5.0
26           1          0.4           1.6          3.4           5.0
27           1          0.2           1.5          3.5           5.2
28           1          0.2           1.4          3.4           5.2
29           1          0.2           1.6          3.2           4.7
30           1          0.2           1.6          3.1           4.8
31           1          0.4           1.5          3.4           5.4
32           1          0.1           1.5          4.1           5.2
33           1          0.2           1.4          4.2           5.5
34           1          0.2           1.5          3.1           4.9
35           1          0.2           1.2          3.2           5.0
36           1          0.2           1.3          3.5           5.5
37           1          0.1           1.4          3.6           4.9
38           1          0.2           1.3          3.0           4.4
39           1          0.2           1.5          3.4           5.1
40           1          0.3           1.3          3.5           5.0
41           1          0.3           1.3          2.3           4.5
42           1          0.2           1.3          3.2           4.4
43           1          0.6           1.6          3.5           5.0
44           1          0.4           1.9          3.8           5.1
45           1          0.3           1.4          3.0           4.8
46           1          0.2           1.6          3.8           5.1
47           1          0.2           1.4          3.2           4.6
48           1          0.2           1.5          3.7           5.3
49           1          0.2           1.4          3.3           5.0

In [8]:
df_versicolor = pd.read_excel('~/Desktop/Iris.xls', sheet_name = 'Data', usecols= range(0,5), header = 0, skiprows = range(1,51), skipfooter = 50)
df_versicolor

Species_No  Petal_width  Petal_length  Sepal_width  Sepal_length
0            2          1.4           4.7          3.2           7.0
1            2          1.5           4.5          3.2           6.4
2            2          1.5           4.9          3.1           6.9
3            2          1.3           4.0          2.3           5.5
4            2          1.5           4.6          2.8           6.5
5            2          1.3           4.5          2.8           5.7
6            2          1.6           4.7          3.3           6.3
7            2          1.0           3.3          2.4           4.9
8            2          1.3           4.6          2.9           6.6
9            2          1.4           3.9          2.7           5.2
10           2          1.0           3.5          2.0           5.0
11           2          1.5           4.2          3.0           5.9
12           2          1.0           4.0          2.2           6.0
13           2          1.4           4.7          2.9           6.1
14           2          1.3           3.6          2.9           5.6
15           2          1.4           4.4          3.1           6.7
16           2          1.5           4.5          3.0           5.6
17           2          1.0           4.1          2.7           5.8
18           2          1.5           4.5          2.2           6.2
19           2          1.1           3.9          2.5           5.6
20           2          1.8           4.8          3.2           5.9
21           2          1.3           4.0          2.8           6.1
22           2          1.5           4.9          2.5           6.3
23           2          1.2           4.7          2.8           6.1
24           2          1.3           4.3          2.9           6.4
25           2          1.4           4.4          3.0           6.6
26           2          1.4           4.8          2.8           6.8
27           2          1.7           5.0          3.0           6.7
28           2          1.5           4.5          2.9           6.0
29           2          1.0           3.5          2.6           5.7
30           2          1.1           3.8          2.4           5.5
31           2          1.0           3.7          2.4           5.5
32           2          1.2           3.9          2.7           5.8
33           2          1.6           5.1          2.7           6.0
34           2          1.5           4.5          3.0           5.4
35           2          1.6           4.5          3.4           6.0
36           2          1.5           4.7          3.1           6.7
37           2          1.3           4.4          2.3           6.3
38           2          1.3           4.1          3.0           5.6
39           2          1.3           4.0          2.5           5.5
40           2          1.2           4.4          2.6           5.5
41           2          1.4           4.6          3.0           6.1
42           2          1.2           4.0          2.6           5.8
43           2          1.0           3.3          2.3           5.0
44           2          1.3           4.2          2.7           5.6
45           2          1.2           4.2          3.0           5.7
46           2          1.3           4.2          2.9           5.7
47           2          1.3           4.3          2.9           6.2
48           2          1.1           3.0          2.5           5.1
49           2          1.3           4.1          2.8           5.7

In [9]:
df_verginica = pd.read_excel('~/Desktop/Iris.xls', sheet_name = 'Data', usecols= range(0,5), header = 0, skiprows = range(1,101))
df_verginica

Species_No  Petal_width  Petal_length  Sepal_width  Sepal_length
0            3          2.5           6.0          3.3           6.3
1            3          1.9           5.1          2.7           5.8
2            3          2.1           5.9          3.0           7.1
3            3          1.8           5.6          2.9           6.3
4            3          2.2           5.8          3.0           6.5
5            3          2.1           6.6          3.0           7.6
6            3          1.7           4.5          2.5           4.9
7            3          1.8           6.3          2.9           7.3
8            3          1.8           5.8          2.5           6.7
9            3          2.5           6.1          3.6           7.2
10           3          2.0           5.1          3.2           6.5
11           3          1.9           5.3          2.7           6.4
12           3          2.1           5.5          3.0           6.8
13           3          2.0           5.0          2.5           5.7
14           3          2.4           5.1          2.8           5.8
15           3          2.3           5.3          3.2           6.4
16           3          1.8           5.5          3.0           6.5
17           3          2.2           6.7          3.8           7.7
18           3          2.3           6.9          2.6           7.7
19           3          1.5           5.0          2.2           6.0
20           3          2.3           5.7          3.2           6.9
21           3          2.0           4.9          2.8           5.6
22           3          2.0           6.7          2.8           7.7
23           3          1.8           4.9          2.7           6.3
24           3          2.1           5.7          3.3           6.7
25           3          1.8           6.0          3.2           7.2
26           3          1.8           4.8          2.8           6.2
27           3          1.8           4.9          3.0           6.1
28           3          2.1           5.6          2.8           6.4
29           3          1.6           5.8          3.0           7.2
30           3          1.9           6.1          2.8           7.4
31           3          2.0           6.4          3.8           7.9
32           3          2.2           5.6          2.8           6.4
33           3          1.5           5.1          2.8           6.3
34           3          1.4           5.6          2.6           6.1
35           3          2.3           6.1          3.0           7.7
36           3          2.4           5.6          3.4           6.3
37           3          1.8           5.5          3.1           6.4
38           3          1.8           4.8          3.0           6.0
39           3          2.1           5.4          3.1           6.9
40           3          2.4           5.6          3.1           6.7
41           3          2.3           5.1          3.1           6.9
42           3          1.9           5.1          2.7           5.8
43           3          2.3           5.9          3.2           6.8
44           3          2.5           5.7          3.3           6.7
45           3          2.3           5.2          3.0           6.7
46           3          1.9           5.0          2.5           6.3
47           3          2.0           5.2          3.0           6.5
48           3          2.3           5.4          3.4           6.2
49           3          1.8           5.1          3.0           5.9

### Importing Data Directly from the Web

We usually want to store a local copy of a data file that we download from the Web, but when data retention is not a priority it is convenient to download the data directly into our running Python environment.

#### Importing Text Files from the Web

The web is the 'wild west' of data formats. However, we can usually expect good behaviour from files that are automatically generated by a service, such as the earthquake report:

In [10]:
df = pd.read_csv('https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_hour.csv')
df.head()

Empty DataFrame
Columns: [time, latitude, longitude, depth, mag, magType, nst, gap, dmin, rms, net, id, updated, place, type, horizontalError, depthError, magError, magNst, status, locationSource, magSource]
Index: []

[0 rows x 22 columns]

#### Importing HTML Files from the Web

Working with unstructured HTML files relies heavily on library functions. This one, however, is well-structured:

In [11]:
url = 'http://www.fdic.gov/bank/individual/failed/banklist.html'
df = pd.read_html(url)
df

[                                             Bank Name                City  \
 0                                 The First State Bank       Barboursville   
 1                                   Ericson State Bank             Ericson   
 2                     City National Bank of New Jersey              Newark   
 3                                        Resolute Bank              Maumee   
 4                                Louisa Community Bank              Louisa   
 5                                 The Enloe State Bank              Cooper   
 6                  Washington Federal Bank for Savings             Chicago   
 7      The Farmers and Merchants State Bank of Argonia             Argonia   
 8                                  Fayette County Bank          Saint Elmo   
 9    Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee   
 10                                      First NBC Bank         New Orleans   
 11                                       Proficio B

#### Importing XML Files from the Web

XML files are semi-structured, but you're at the mercy of the file creator. If every record has the same format it will be much easier, but practical applications often require a lot of custom code. Here is an example that includes a nice parser class: http://www.austintaylor.io/lxml/python/pandas/xml/dataframe/2016/07/08/convert-xml-to-pandas-dataframe/

#### Importing JSON Files from the Web

Like XML, JSON files are semi-structured and may require work to capture the schema into a dataframe. Here is a simple example: 

In [12]:
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/data.json'

# Load the first sheet of the JSON file into a data frame
df = pd.read_json(url, orient = 'columns')
df.head()

integer            datetime  category
0         5 2015-01-01 00:00:00         0
1         5 2015-01-01 00:00:01         0
10        5 2015-01-01 00:00:10         0
11        5 2015-01-01 00:00:11         0
12        8 2015-01-01 00:00:12         0

## Part 2: Data Munging

Data munging is manipulating data to get it into a form that we can start running analyses on (which usually means getting the data into a DataFrame). Before we get to this stage, we may need to remove headers or footers, transpose columns to rows, split wide data tables into long ones, and so on. (Nb. Excel files can be particularly troublesome, because users can format their data in mixed, complex shapes.) Essentially, we need to follow Hadley Wickham's guidelines for tidy datasets (http://vita.had.co.nz/papers/tidy-data.html):

The end goal of the cleaning data process:

- each variable should be in one column
- each observation should comprise one row
- each type of observational unit should form one table
- include key columns for linking multiple tables
- the top row contains (sensible) variable names
- in general, save data as one file per table


### Dataset Morphology

Once we have our dataset in a DataFrame (or Series, if our data is only 1-dimensional), we can start examining its size and content.

How many rows and columns are in `bikes`?

In [13]:
#ANSWER
rows, cols = bikes.shape
print(f'There are {rows} rows and {cols} columns')

There are 17379 rows and 17 columns


What are the column names in `bikes`?

In [16]:
#ANSWER
list(bikes.columns)

['instant',
 'dteday',
 'season',
 'yr',
 'mnth',
 'hr',
 'holiday',
 'weekday',
 'workingday',
 'weathersit',
 'temp',
 'atemp',
 'hum',
 'windspeed',
 'casual',
 'registered',
 'cnt']

What are the data types of these columns?

In [17]:
#ANSWER
bikes.dtypes

instant         int64
dteday         object
season          int64
yr              int64
mnth            int64
hr              int64
holiday         int64
weekday         int64
workingday      int64
weathersit      int64
temp          float64
atemp         float64
hum           float64
windspeed     float64
casual          int64
registered      int64
cnt             int64
dtype: object

What is the (row) index for this DataFrame?

In [18]:
#ANSWER
bikes.index

RangeIndex(start=0, stop=17379, step=1)

https://www.dataquest.io/blog/python-json-tutorial/

## Slicing and Dicing

It is often preferable to refer to DataFrame columns by name, but there is more than one way to do this. 
Do `bikes['season']` and `bikes[['season']]` give the same object? Demonstrate:

In [19]:
#ANSWER
bikes['season']

0        1
1        1
2        1
3        1
4        1
5        1
6        1
7        1
8        1
9        1
10       1
11       1
12       1
13       1
14       1
15       1
16       1
17       1
18       1
19       1
20       1
21       1
22       1
23       1
24       1
25       1
26       1
27       1
28       1
29       1
        ..
17349    1
17350    1
17351    1
17352    1
17353    1
17354    1
17355    1
17356    1
17357    1
17358    1
17359    1
17360    1
17361    1
17362    1
17363    1
17364    1
17365    1
17366    1
17367    1
17368    1
17369    1
17370    1
17371    1
17372    1
17373    1
17374    1
17375    1
17376    1
17377    1
17378    1
Name: season, Length: 17379, dtype: int64

In [20]:
bikes[['season']]

season
0           1
1           1
2           1
3           1
4           1
5           1
6           1
7           1
8           1
9           1
10          1
11          1
12          1
13          1
14          1
15          1
16          1
17          1
18          1
19          1
20          1
21          1
22          1
23          1
24          1
25          1
26          1
27          1
28          1
29          1
...       ...
17349       1
17350       1
17351       1
17352       1
17353       1
17354       1
17355       1
17356       1
17357       1
17358       1
17359       1
17360       1
17361       1
17362       1
17363       1
17364       1
17365       1
17366       1
17367       1
17368       1
17369       1
17370       1
17371       1
17372       1
17373       1
17374       1
17375       1
17376       1
17377       1
17378       1

[17379 rows x 1 columns]

How would we use object notation to show the first 4 rows of `atemp`?

In [29]:
#ANSWER
bikes.loc[0:3,'atemp']

0    0.2879
1    0.2727
2    0.2727
3    0.2879
Name: atemp, dtype: float64

Algorithms that loop over multiple columns often access DataFrame columns by index. However, none of the following work (try them out by uncommenting / removing the "#E: " ): 

In [33]:
bikes[[0]]
#E: bikes[0]
#E: bikes[0,0]
#E: bikes[[0,0]]

KeyError: "None of [Int64Index([0], dtype='int64')] are in the [columns]"

What is the correct way to access the 1st row of the DataFrame by its index?

In [37]:
#ANSWER
bikes.iloc[0, :]

instant                1
dteday        2011-01-01
season                 1
yr                     0
mnth                   1
hr                     0
holiday                0
weekday                6
workingday             0
weathersit             1
temp                0.24
atemp             0.2879
hum                 0.81
windspeed              0
casual                 3
registered            13
cnt                   16
Name: 0, dtype: object

What is the correct way to access the 2nd column of the DataFrame by its index?

In [198]:
#ANSWER
bikes.iloc[:,1]

0        2011-01-01
1        2011-01-01
2        2011-01-01
3        2011-01-01
4        2011-01-01
5        2011-01-01
6        2011-01-01
7        2011-01-01
8        2011-01-01
9        2011-01-01
10       2011-01-01
11       2011-01-01
12       2011-01-01
13       2011-01-01
14       2011-01-01
15       2011-01-01
16       2011-01-01
17       2011-01-01
18       2011-01-01
19       2011-01-01
20       2011-01-01
21       2011-01-01
22       2011-01-01
23       2011-01-01
24       2011-01-02
25       2011-01-02
26       2011-01-02
27       2011-01-02
28       2011-01-02
29       2011-01-02
            ...    
17349    2012-12-30
17350    2012-12-30
17351    2012-12-30
17352    2012-12-30
17353    2012-12-30
17354    2012-12-30
17355    2012-12-31
17356    2012-12-31
17357    2012-12-31
17358    2012-12-31
17359    2012-12-31
17360    2012-12-31
17361    2012-12-31
17362    2012-12-31
17363    2012-12-31
17364    2012-12-31
17365    2012-12-31
17366    2012-12-31
17367    2012-12-31


## Handling Missing Values

What is the Pandas `isnull` function for? 

?
ANSWER: It checks whether the identified cell/row/column has a 'null' value

We can apply `isnull` to the `bikes` DataFrame to show the result for every element:

In [39]:
bikes.isnull().head()

instant  dteday  season     yr   mnth     hr  holiday  weekday  workingday  \
0    False   False   False  False  False  False    False    False       False   
1    False   False   False  False  False  False    False    False       False   
2    False   False   False  False  False  False    False    False       False   
3    False   False   False  False  False  False    False    False       False   
4    False   False   False  False  False  False    False    False       False   

   weathersit   temp  atemp    hum  windspeed  casual  registered    cnt  
0       False  False  False  False      False   False       False  False  
1       False  False  False  False      False   False       False  False  
2       False  False  False  False      False   False       False  False  
3       False  False  False  False      False   False       False  False  
4       False  False  False  False      False   False       False  False

However, we usually start at a higher level. How many nulls are in `bikes` altogether?

In [49]:
#ANSWER
bikes.isnull().values.sum()

0

If this result were nonzero we would next want to find out which columns contained nulls. How can this be done in one line of code?

In [50]:
#ANSWER
bikes.isnull().values.any()

False

What is the Numpy object `nan` used for? (Write a descriptive answer.)

?
ANSWER: Marking a data point as invalid.

Write (and verify) a function that performs scalar division with built-in handling of the edge case (i.e. return a value instead of just trapping the error):

In [55]:
#ANSWER
def scal_div(x,y):
    '''Divides x by y. Args must be integer or float, y cannot be 0'''
    if y == 0:
        raise ValueError('y cannot be 0, cannot divide by 0')
    else:
        result = x / y
        return result
        

In [59]:
print(scal_div(10,2))

5.0


In [60]:
print(scal_div(10,0))

ValueError: y cannot be 0, cannot divide by 0

Apply the Pandas `isna` function to the following data objects:

In [61]:
x = 2.3
y = np.nan
print(x, y)

2.3 nan


In [63]:
#ANSWER
pd.isna(x)

False

In [64]:
pd.isna(y)

True

In [65]:
array = np.array([[1, np.nan, 3], [4, 5, np.nan]])
print(array)

[[ 1. nan  3.]
 [ 4.  5. nan]]


In [66]:
#ANSWER
pd.isna(array)

array([[False,  True, False],
       [False, False,  True]])

How is the pandas I/O parameter `na_values` used?

? ANSWER: To ID the character or value in the uploaded document that corresponds to a NA or NaN value

## Data Profiling

### Counts

When there are categorical variables in a dataset we will want to know how many possible values there are in each column. (Nb. If the dataset is a sample of a larger one, our sample may not capture all possible values of every categorical.)

How many (different) seasons are in `bikes`?

In [76]:
#ANSWER
bikes.season.unique()

array([1, 2, 3, 4], dtype=int64)

### Ranges

Print the range of the `instant`, `dteday`, and `windspeed` columns: 

In [105]:
#ANSWER
instantrange = bikes.instant.max() - bikes.instant.min()
instantrange

17378

In [106]:
startdate = bikes.dteday.min()
enddate = bikes.dteday.max()
print(bikes.dteday.min(), bikes.dteday.max())

2011-01-01 2012-12-31


In [107]:
windrange = bikes.windspeed.max() - bikes.windspeed.min()
windrange

0.8507

Compute and print the overall minimum and maximum of the numeric data columns:

In [88]:
bikes_min, bikes_max = (min(bikes.min()), max(bikes.max()))
bikes_min, bikes_max

TypeError: '<' not supported between instances of 'str' and 'int'

In [87]:
bikes.max()

instant            17379
dteday        2012-12-31
season                 4
yr                     1
mnth                  12
hr                    23
holiday                1
weekday                6
workingday             1
weathersit             4
temp                   1
atemp                  1
hum                    1
windspeed         0.8507
casual               367
registered           886
cnt                  977
dtype: object

### Quantiles

Pandas makes computing quantiles easy. This is how to get the median of a Series:

In [112]:
bikes['atemp'].quantile(0.5)

0.4848

Of course, the `quantiles` method can take a tuple as its argument. Compute the 10th, 25th, 50th, 75th, and 90th percentiles in one line of code: 

In [115]:
#ANSWER
bikes['atemp'].quantile((0.1, 0.25, 0.5, 0.75, 0.9))

0.10    0.2424
0.25    0.3333
0.50    0.4848
0.75    0.6212
0.90    0.6970
Name: atemp, dtype: float64

### Cuts

Sometimes we want to split the sample not by the quantiles of the distribution but by the range of the data. Let's take a closer look at `atemp`:

In [116]:
type(bikes['atemp'])

pandas.core.series.Series

In [117]:
bikes.sample(5)

instant      dteday  season  yr  mnth  hr  holiday  weekday  \
6253      6254  2011-09-23       4   0     9   3        0        5   
4768      4769  2011-07-22       3   0     7  14        0        5   
10394    10395  2012-03-14       1   1     3   5        0        3   
5011      5012  2011-08-01       3   0     8  17        0        1   
4482      4483  2011-07-10       3   0     7  16        0        0   

       workingday  weathersit  temp   atemp   hum  windspeed  casual  \
6253            1           2  0.60  0.5000  1.00     0.0000       3   
4768            1           1  0.96  1.0000  0.48     0.2985      24   
10394           1           1  0.44  0.4394  0.82     0.1343       2   
5011            1           1  0.76  0.6818  0.45     0.2985      69   
4482            0           1  0.84  0.7576  0.41     0.2836     128   

       registered  cnt  
6253            5    8  
4768           77  101  
10394          25   27  
5011          445  514  
4482          244  372

Suppose we decide to sort these values into 4 bins of equal width, but we want to apply the resulting groups to the entire DataFrame. Basically, we need to add a row label that indcates which bin each sample belongs in. Let's call this label "atemp_level", and use the `cut` method to populate it:

In [122]:
atemp_level = pd.cut(bikes['atemp'], bins = 4)     
atemp_level

0           (0.25, 0.5]
1           (0.25, 0.5]
2           (0.25, 0.5]
3           (0.25, 0.5]
4           (0.25, 0.5]
5           (0.25, 0.5]
6           (0.25, 0.5]
7           (0.25, 0.5]
8           (0.25, 0.5]
9           (0.25, 0.5]
10          (0.25, 0.5]
11          (0.25, 0.5]
12          (0.25, 0.5]
13          (0.25, 0.5]
14          (0.25, 0.5]
15          (0.25, 0.5]
16          (0.25, 0.5]
17          (0.25, 0.5]
18          (0.25, 0.5]
19          (0.25, 0.5]
20          (0.25, 0.5]
21          (0.25, 0.5]
22          (0.25, 0.5]
23          (0.25, 0.5]
24          (0.25, 0.5]
25          (0.25, 0.5]
26          (0.25, 0.5]
27          (0.25, 0.5]
28          (0.25, 0.5]
29          (0.25, 0.5]
              ...      
17349    (-0.001, 0.25]
17350       (0.25, 0.5]
17351    (-0.001, 0.25]
17352    (-0.001, 0.25]
17353    (-0.001, 0.25]
17354    (-0.001, 0.25]
17355    (-0.001, 0.25]
17356    (-0.001, 0.25]
17357    (-0.001, 0.25]
17358    (-0.001, 0.25]
17359    (-0.001

What is `atemp_level`?

#ANSWER
A new row which contains the bins that each 'atemp' value lies within.

Here is a random sample of `atemp_level`:

In [121]:
atemp_level.sample(5)          

8405        (0.25, 0.5]
17067       (0.25, 0.5]
16496    (-0.001, 0.25]
16422       (0.25, 0.5]
15023       (0.25, 0.5]
Name: atemp, dtype: category
Categories (4, interval[float64]): [(-0.001, 0.25] < (0.25, 0.5] < (0.5, 0.75] < (0.75, 1.0]]

So, by default, `cut` produces labels that indicate the bin boundaries for each element in the series it was applied to. Usually, we will specify labels that are appropriate to the discretisation we are applying:

In [123]:
atemp_level = pd.cut(bikes['atemp'], bins = 4, labels = ["cool", "mild", "warm", "hot"])
atemp_level.sample(5)          

69       cool
8050     mild
14083    warm
4504      hot
9615     mild
Name: atemp, dtype: category
Categories (4, object): [cool < mild < warm < hot]

Incorporate the new `atemp_level` column into the `bikes` DataFrame and use it to count the number of "mild" `atemp` entries in `season` 2:

In [127]:
#ANSWER
bikes["atemp_level"] = atemp_level
bikes.head()

instant      dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1   0        0        6           0   
1        2  2011-01-01       1   0     1   1        0        6           0   
2        3  2011-01-01       1   0     1   2        0        6           0   
3        4  2011-01-01       1   0     1   3        0        6           0   
4        5  2011-01-01       1   0     1   4        0        6           0   

   weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  \
0           1  0.24  0.2879  0.81        0.0       3          13   16   
1           1  0.22  0.2727  0.80        0.0       8          32   40   
2           1  0.22  0.2727  0.80        0.0       5          27   32   
3           1  0.24  0.2879  0.75        0.0       3          10   13   
4           1  0.24  0.2879  0.75        0.0       0           1    1   

  atemp_level  
0        mild  
1        mild  
2        mild  
3        mild  
4        mild

In [134]:
np.sum(bikes["atemp_level"] == 'mild')

7507

*Nb. The `atemp_level` variable we created is what the R language calls a "factor". Pandas has introduced a new data type called "category" that is similar to R's factors.*

# Synthetic Data

Sometimes we may want to generate test data, or we may need to initalise a series, matrix, or data frame for input to an algorithm. Numpy has several methods we can use for this.

Execute the following, then check the shape and content of each variable:

In [136]:
# Creating arrays with initial values
a = np.zeros((3))
b = np.ones((1,3))
c = np.random.randint(1,10,(2,3,4))   # randint(low, high, size)
d = np.arange(4)
e = np.array( [[1,2,3,4], [5,6,7,8]] )

In [143]:
# Cleaning Data
print(a.shape)
print(a)
print(b.shape)
print(b)
print(c.shape)
print(c)
print(d.shape)
print(d)
print(e.shape)
print(e)

(3,)
[0. 0. 0.]
(1, 3)
[[1. 1. 1.]]
(2, 3, 4)
[[[4 2 5 8]
  [9 9 2 8]
  [1 6 5 3]]

 [[2 4 1 7]
  [5 2 2 4]
  [1 8 6 6]]]
(4,)
[0 1 2 3]
(2, 4)
[[1 2 3 4]
 [5 6 7 8]]


## Load Data

Load rock.csv and clean the dataset.

In [144]:
rockdf = pd.read_csv('~/Desktop/rock.csv')
rockdf.head()

Song Clean ARTIST CLEAN Release Year  \
0        Caught Up in You  .38 Special         1982   
1            Fantasy Girl  .38 Special          NaN   
2         Hold On Loosely  .38 Special         1981   
3  Rockin' Into the Night  .38 Special         1980   
4       Art For Arts Sake         10cc         1975   

                                COMBINED  First?  Year?  PlayCount  F*G  
0        Caught Up in You by .38 Special       1      1         82   82  
1            Fantasy Girl by .38 Special       1      0          3    0  
2         Hold On Loosely by .38 Special       1      1         85   85  
3  Rockin' Into the Night by .38 Special       1      1         18   18  
4              Art For Arts Sake by 10cc       1      1          1    1

## Check Column Names

Check column names and clean.

In [145]:
rockdf.columns

Index(['Song Clean', 'ARTIST CLEAN', 'Release Year', 'COMBINED', 'First?',
       'Year?', 'PlayCount', 'F*G'],
      dtype='object')

In [147]:
rockdf.rename(columns = {"First?": "First", "Year?":"Year"}, inplace = True)
rockdf.head()

Song Clean ARTIST CLEAN Release Year  \
0        Caught Up in You  .38 Special         1982   
1            Fantasy Girl  .38 Special          NaN   
2         Hold On Loosely  .38 Special         1981   
3  Rockin' Into the Night  .38 Special         1980   
4       Art For Arts Sake         10cc         1975   

                                COMBINED  First  Year  PlayCount  F*G  
0        Caught Up in You by .38 Special      1     1         82   82  
1            Fantasy Girl by .38 Special      1     0          3    0  
2         Hold On Loosely by .38 Special      1     1         85   85  
3  Rockin' Into the Night by .38 Special      1     1         18   18  
4              Art For Arts Sake by 10cc      1     1          1    1

# Replace Null Values With 0

Check 'release' column whether this column have any null value or not. Replace null value with 0.

In [156]:
rockdf['Release Year'].fillna(0, inplace = True)
rockdf.head()

Song Clean ARTIST CLEAN Release Year  \
0        Caught Up in You  .38 Special         1982   
1            Fantasy Girl  .38 Special            0   
2         Hold On Loosely  .38 Special         1981   
3  Rockin' Into the Night  .38 Special         1980   
4       Art For Arts Sake         10cc         1975   

                                COMBINED  First  Year  PlayCount  F*G  
0        Caught Up in You by .38 Special      1     1         82   82  
1            Fantasy Girl by .38 Special      1     0          3    0  
2         Hold On Loosely by .38 Special      1     1         85   85  
3  Rockin' Into the Night by .38 Special      1     1         18   18  
4              Art For Arts Sake by 10cc      1     1          1    1

# Check Datatypes of Dataset

Check datatypes of the dataset. Is there any column which should be int instead of object? Fix the column. 

In [161]:
#Check the column types
rockdf.dtypes

Song Clean      object
ARTIST CLEAN    object
Release Year    object
COMBINED        object
First            int64
Year             int64
PlayCount        int64
F*G              int64
dtype: object

In [170]:
#Find the value which does not allow int conversion
rockdf.loc[rockdf['Release Year'] == 'SONGFACTS.COM']

Song Clean    ARTIST CLEAN   Release Year  \
1504  Bullfrog Blues  Rory Gallagher  SONGFACTS.COM   

                              COMBINED  First  Year  PlayCount  F*G  
1504  Bullfrog Blues by Rory Gallagher      1     1          1    1

In [173]:
#Replace the wrong value with a 0 (which can be converted to int)
rockdf["Release Year"].replace({'SONGFACTS.COM': '0'}, inplace=True)

In [181]:
#Convert column to int
introck = rockdf.astype({'Release Year': int})
introck.dtypes

Song Clean      object
ARTIST CLEAN    object
Release Year     int32
COMBINED        object
First            int64
Year             int64
PlayCount        int64
F*G              int64
dtype: object

In [177]:
#Recheck column types
rockdf.dtypes

Song Clean      object
ARTIST CLEAN    object
Release Year    object
COMBINED        object
First            int64
Year             int64
PlayCount        int64
F*G              int64
dtype: object

# Check Min, Max of Each Column

Is there any illogical value in any column? How can we fix that?

In [191]:
introck.describe()

Release Year   First         Year    PlayCount          F*G
count   2230.000000  2230.0  2230.000000  2230.000000  2230.000000
mean    1465.331390     1.0     0.741256    16.872646    15.048430
std      867.196161     0.0     0.438043    25.302972    25.288366
min        0.000000     1.0     0.000000     0.000000     0.000000
25%        0.000000     1.0     0.000000     1.000000     0.000000
50%     1973.000000     1.0     1.000000     4.000000     3.000000
75%     1981.000000     1.0     1.000000    21.000000    18.000000
max     2014.000000     1.0     1.000000   142.000000   142.000000

# Write Some Functions

## Write a function that will take a row of a DataFrame and print out the song, artist, and whether or not the release date is < 1970

In [201]:
def rowrelease(df, rownum):
    song = df.loc[rownum,'Song Clean']
    artist = df.loc[rownum, 'ARTIST CLEAN']
    reldate = df.loc[rownum, 'Release Year'] < 1970
    
    print(f'It is {reldate} that {song}, by {artist} was released before 1970')

In [203]:
rowrelease(introck, 2)

It is False that Hold On Loosely, by .38 Special was released before 1970


In [202]:
introck.head()

Song Clean ARTIST CLEAN  Release Year  \
0        Caught Up in You  .38 Special          1982   
1            Fantasy Girl  .38 Special             0   
2         Hold On Loosely  .38 Special          1981   
3  Rockin' Into the Night  .38 Special          1980   
4       Art For Arts Sake         10cc          1975   

                                COMBINED  First  Year  PlayCount  F*G  
0        Caught Up in You by .38 Special      1     1         82   82  
1            Fantasy Girl by .38 Special      1     0          3    0  
2         Hold On Loosely by .38 Special      1     1         85   85  
3  Rockin' Into the Night by .38 Special      1     1         18   18  
4              Art For Arts Sake by 10cc      1     1          1    1

In [200]:
introck.loc[1,'Song Clean']

'Fantasy Girl'

## Write a function that converts cells in a DataFrame to float and otherwise replaces them with np.nan

In [211]:
#Don't know how to do this
def floatornan(df):
    '''Convert all cells to float if possible, otherwise replace with NaN'''
    for i in df.loc[:,:]:
        if type(i) == 'int64' or type(i) == 'int32':
            i.astype(float)
        if type(i) != 'int64' or type(i) != 'int32':
            i = np.nan
            
    return df
        

In [215]:
nanrock = floatornan(introck)
nanrock.dtypes

Song Clean      object
ARTIST CLEAN    object
Release Year     int32
COMBINED        object
First            int64
Year             int64
PlayCount        int64
F*G              int64
dtype: object

## Apply these functions to your dataset

In [ ]:
#Couldn't work out the function

## Describe the new float-only DataFrame.



> 
>
>




>


>


>




---



---



> > > > > > > > > © 2019 Institute of Data


---



---



