<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

# Lab 4.1.2 Linear Regression

## Prediction of House Price Using Linear Regression

### Data

The Sacramento real estate transactions file is a list of 985 real estate transactions in the Sacramento area reported over a five-day period, as reported by the Sacramento Bee.

In [1]:
import pandas as pd
import numpy as np
import pandas as pd

%matplotlib inline

### 1. Explore Data

Perform EDA on this dataset. Find Dependent and Independent Variables to predict house price.

In [2]:
# Read CSV
house_csv = pd.read_csv("C:\\temp\\Data Science\\IOD\\data\\Sacramento_transactions.csv")

### 2. Predict Price

We are going to predict `price` from available information.

#### 2.1 What is the Target Variable? Why?

In [31]:
# ANSWER

#### 2.2 List all possible variables which might be Independent/Predictor variable.

In [32]:
# ANSWER

#### 2.2 Find correlation between variables

Find correlation between variables. Which is the best predictor? Why? State your reason.

In [3]:
# ANSWER
house_csv.corr()

zip      beds     baths    sq__ft     price  latitude  \
zip        1.000000  0.125319  0.069165  0.130108 -0.093353 -0.290389   
beds       0.125319  1.000000  0.839650  0.684041  0.342024 -0.291307   
baths      0.069165  0.839650  1.000000  0.665690  0.416208 -0.235792   
sq__ft     0.130108  0.684041  0.665690  1.000000  0.333897 -0.383274   
price     -0.093353  0.342024  0.416208  0.333897  1.000000 -0.039573   
latitude  -0.290389 -0.291307 -0.235792 -0.383274 -0.039573  1.000000   
longitude -0.539904 -0.053993  0.016582 -0.177742  0.284485  0.387925   

           longitude  
zip        -0.539904  
beds       -0.053993  
baths       0.016582  
sq__ft     -0.177742  
price       0.284485  
latitude    0.387925  
longitude   1.000000

In [8]:
house_csv.corrwith(house_csv['price']).sort_values(ascending=False)

price        1.000000
baths        0.416208
beds         0.342024
sq__ft       0.333897
longitude    0.284485
latitude    -0.039573
zip         -0.093353
dtype: float64

#### 2.3 Find Coefficient and Intercept using Linear Regression

Using LinearRegression of sklearn.linear_model package find Coefficient and Intercept.

Create an instance of LinearRegression.

Explore following methods:

- fit
- predict
- score

In [9]:
from sklearn.linear_model import LinearRegression

##### 2.3.1 Fit predictor and target variables using linear regression 

In [14]:
# ANSWER

X = house_csv['sq__ft'].values.reshape(-1,1)
Y = house_csv['price']

lr = LinearRegression()
lr.fit(X, Y)
lr.predict(X)


array([208206.78418661, 226133.29392351, 206040.43859907, 209073.32242163,
       206094.59723876, 223696.15513753, 222721.29962314, 226674.8803204 ,
       213893.44135391, 224995.96249005, 212160.36488387, 232740.64796551,
       210102.33657571, 218171.9738893 , 218280.29116868, 224346.05881379,
       208640.05330412, 205986.27995938, 194775.44154385, 236369.27682465,
       223479.52057878, 234906.99355306, 230086.87462078, 249638.14354834,
       211727.09576636, 221854.76138812, 215084.93142705, 223533.67921846,
       237669.08417717, 230520.14373828, 219200.98804338, 225320.91432819,
       237669.08417717, 223371.2032994 , 219200.98804338, 239727.11248533,
       221529.80954999, 242651.67902852, 224995.96249005, 204090.72757028,
       233553.02756084, 228299.63951105, 220121.68491809, 219417.62260214,
       248879.9225927 , 223587.83785815, 248500.81211488, 268810.30199808,
       252616.8687312 , 242922.47222696, 227270.62535697, 249042.39851176,
       242164.25127132, 2

##### 2.3.2 Find R Score

Find $R^2$ Using ```score``` method of Linear Regression.

In [15]:
# ANSWER
lr.score(X, Y)

0.11148717682951437

### 3. Splitting Data

In [16]:
from sklearn.model_selection import train_test_split

#### 3.1 Create training and testing subsets

Hint: Using `train_test_split` Library.

```
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
```

In [17]:
# ANSWER
## Create training and testing subsets

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=42 )

#### 3.2 Check Shape, Sample of Test Train Data

In [19]:
# ANSWER
## Check training/test data
print('X Train', X_train.shape)
print('Y Train', y_train.shape)
print('X Test', X_test.shape)
print('Y Test', y_test.shape)



X Train (659, 1)
Y Train (659,)
X Test (326, 1)
Y Test (326,)


In [22]:
X_train

array([[1758],
       [1643],
       [2354],
       [   0],
       [1354],
       [   0],
       [ 958],
       [1232],
       [ 888],
       [1440],
       [1051],
       [1266],
       [2575],
       [1915],
       [1718],
       [2109],
       [   0],
       [2052],
       [1039],
       [2169],
       [2110],
       [1691],
       [1316],
       [1380],
       [   0],
       [ 722],
       [   0],
       [1219],
       [   0],
       [1686],
       [1627],
       [ 722],
       [1104],
       [1120],
       [1264],
       [   0],
       [3173],
       [   0],
       [1751],
       [3433],
       [2592],
       [   0],
       [1137],
       [1816],
       [1922],
       [   0],
       [1450],
       [   0],
       [ 952],
       [1207],
       [   0],
       [3612],
       [   0],
       [1943],
       [1407],
       [1766],
       [2457],
       [   0],
       [ 901],
       [1872],
       [2004],
       [1578],
       [1513],
       [1302],
       [ 623],
       [1590],
       [14

#### 3.3 Using Linear Regression Find The Score

1. Fit model using X_train, y_train
2. Find score using x_test, y_test

In [29]:
# ANSWER
lr.fit(X_train, y_train)

print('Coeffiecient',lr.coef_)
print('Intercept', lr.intercept_)

Coeffiecient [47.43508406]
Intercept 166482.3414496886


In [30]:
lr.score(X_train, y_train)

0.08614711011567588

In [31]:
lr.score(X_test, y_test)

0.13602012247180006

### 3. Predict House Price

Let's assume we have information of following house:

- street:	1140 EDMONTON DR
- city:	SACRAMENTO
- zip:	95833
- state:	CA
- beds:	3
- baths:	2
- sq__ft:	1204
- type:	Residential

**Predict the price of this house using linear regression model.**

In [40]:
# ANSWER
x =[[1204]]
ypredict = lr.predict(x)
ypredict

array([223594.18266381])

In [43]:
Y_predicts = lr.predict(X_test)
Y_predicts[:5]

array([209458.52761247, 279472.71169224, 259549.97638499, 248971.95263852,
       238915.71481676])

In [44]:
from sklearn.metrics import mean_squared_error

mean_squared_error(y_test, Y_predicts, squared=True)

18951801967.76203



---



---



> > > > > > > > > © 2019 Institute of Data


---



---



